package cn.oursnail.happybike.entity;

import java.math.BigDecimal;

public class RideFee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ride_fee.id
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ride_fee.min_unit
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    private Integer minUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ride_fee.fee
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ride_fee.bike_type
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    private Byte bikeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ride_fee.id
     *
     * @return the value of ride_fee.id
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ride_fee.id
     *
     * @param id the value for ride_fee.id
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ride_fee.min_unit
     *
     * @return the value of ride_fee.min_unit
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public Integer getMinUnit() {
        return minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ride_fee.min_unit
     *
     * @param minUnit the value for ride_fee.min_unit
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public void setMinUnit(Integer minUnit) {
        this.minUnit = minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ride_fee.fee
     *
     * @return the value of ride_fee.fee
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ride_fee.fee
     *
     * @param fee the value for ride_fee.fee
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ride_fee.bike_type
     *
     * @return the value of ride_fee.bike_type
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public Byte getBikeType() {
        return bikeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ride_fee.bike_type
     *
     * @param bikeType the value for ride_fee.bike_type
     *
     * @mbggenerated Thu Mar 15 14:09:42 CST 2018
     */
    public void setBikeType(Byte bikeType) {
        this.bikeType = bikeType;
    }
}