package cn.oursnail.happybike.dao.mapper;

import cn.oursnail.happybike.entity.Bike;

public interface BikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    int insert(Bike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    int insertSelective(Bike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    Bike selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    int updateByPrimaryKeySelective(Bike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bike
     *
     * @mbggenerated Thu Mar 15 13:46:47 CST 2018
     */
    int updateByPrimaryKey(Bike record);

    Bike selectByBikeNo(Long bikeNumber);
}