package cn.oursnail.happybike.dao.mapper;

import cn.oursnail.happybike.entity.RideRecord;

import java.util.List;

public interface RideRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    int insert(RideRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    int insertSelective(RideRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    RideRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    int updateByPrimaryKeySelective(RideRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ride_record
     *
     * @mbggenerated Thu Mar 15 13:52:08 CST 2018
     */
    int updateByPrimaryKey(RideRecord record);

    RideRecord selectRecordNotClosed(Long userId);

    RideRecord selectBikeRecordOnGoing(Long bikeNumber);

    List<RideRecord> selectRideRecordPage(Long userId, Long lastId);
}