package cn.oursnail.happybike.dao.mapper;

import cn.oursnail.happybike.entity.Wallet;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    Wallet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated Thu Mar 15 13:56:29 CST 2018
     */
    int updateByPrimaryKey(Wallet record);

    Wallet selectByUserId(Long userId);
}